[workspace]
authors = ["KoNeu <no_mail>"]
channels = ["conda-forge"]
name = "starter"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "pytest starter/tests/ --cov=starter --cov-report=term-missing"
lint = "flake8 starter/"
serve = "uvicorn starter.starter.main:app --reload"
train = "python starter/starter/train_model.py"

[dependencies]
dvc = ">=3.67.0,<4"
flake8 = ">=7.3.0,<8"

[pypi-dependencies]
fastapi = "==0.117.1"
uvicorn = { version = "==0.36.0", extras = ["standard"] }
pydantic = ">=2.11.9"
pytest = "==8.4.2"
pytest-cov = "*"
pytest-asyncio = "==1.2.0"
httpx = "==0.28.1"
requests = "==2.32.5"
pandas = "==2.3.2"
numpy = "==2.3.3"
matplotlib = "==3.10.6"
seaborn = "==0.13.2"
scikit-learn = "==1.7.2"
jupyter = "==1.1.1"
ipykernel = "==6.30.1"
nbformat = "==5.10.4"
aequitas = "==1.1.0"
altair = ">=5.5.0"
flask = "==0.12.2"
flask-bootstrap = "==3.3.7.1"
python-multipart = "==0.0.20"
httplib2 = "==0.31.0"
torch=">=1.0.2"
torchvision=">=0.20"
